// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIgGwDpiFMhNtREt1KCcsmpZAxDfPV94',
    appId: '1:661554472447:web:8767f667dbe6f010fcb3ca',
    messagingSenderId: '661554472447',
    projectId: 'randommelody-e5396',
    authDomain: 'randommelody-e5396.firebaseapp.com',
    storageBucket: 'randommelody-e5396.appspot.com',
    measurementId: 'G-TZMJKN8LV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WffL1t1kf_qmHkL5_Ir6_Ni1r4W_cu4',
    appId: '1:661554472447:android:f97c3db66d5fb580fcb3ca',
    messagingSenderId: '661554472447',
    projectId: 'randommelody-e5396',
    storageBucket: 'randommelody-e5396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsjhTixMDCDJ-soVvq7LMWzPO4875diy4',
    appId: '1:661554472447:ios:0a31dd250c3b1ff0fcb3ca',
    messagingSenderId: '661554472447',
    projectId: 'randommelody-e5396',
    storageBucket: 'randommelody-e5396.appspot.com',
    iosBundleId: 'com.yuriiukrainets.randommelody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsjhTixMDCDJ-soVvq7LMWzPO4875diy4',
    appId: '1:661554472447:ios:c44c6cef36d5ac35fcb3ca',
    messagingSenderId: '661554472447',
    projectId: 'randommelody-e5396',
    storageBucket: 'randommelody-e5396.appspot.com',
    iosBundleId: 'com.yuriiukrainets.randommelody.RunnerTests',
  );
}
